name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Close PRs that introduce an index file into the repository.
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - filesMatchPattern:
              matchAny: true
              pattern: articles/index.*
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - You tried to add an index file to this repository; this is not permitted so your pull request will be closed automatically.
          - closePullRequest

      - description: Close PRs to the "personalizer" and "responsible-ai" folders where the author isn't a member of the MicrosoftDocs org (i.e. PRs in public repo).
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - or:
            - filesMatchPattern:
                matchAny: true
                pattern: articles/ai-foundry/responsible-ai/*
            - filesMatchPattern:
                matchAny: true
                pattern: articles/ai-services/personalizer/*
          - not:
              activitySenderHasAssociation:
                association: Member
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - Pull requests that modify files in this folder aren't accepted from public contributors.
          - closePullRequest

      - description: \@mention specific people when a PR is opened in the "personalizer" or "responsible-ai" folder.
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          -or:
            - filesMatchPattern:
                matchAny: true
                pattern: articles/ai-foundry/responsible-ai/*
            - filesMatchPattern:
                matchAny: true
                pattern: articles/ai-services/personalizer/*
          - activitySenderHasAssociation:
              association: Member
          - not:
              or:
                - isActivitySender:
                    user: eric-urban
                - isActivitySender:
                    user: nitinme
                - isActivitySender:
                    user: mrbullwinkle
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - Please don't sign off on this PR. The area owners will sign off once they've reviewed your contribution.
          - mentionUsers:
              mentionees:
                - eric-urban
                - nitinme
                - mrbullwinkle
              replyTemplate: ${mentionees} - Please review this PR and sign off when you're ready to merge it.
              assignMentionees: True # This part probably won't work since the bot doesn't have write perms.
          - addLabel:
              label: needs-human-review

      - description: \@mention specific people when a PR is opened in the "ai-services/responsible-ai" folder.
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - filesMatchPattern:
              matchAny: true
              pattern: articles/ai-services/responsible-ai/*
          - activitySenderHasAssociation:
              association: Member
          - not:
              or:
                - isActivitySender:
                    user: eric-urban
                - isActivitySender:
                    user: nitinme
                - isActivitySender:
                    user: mrbullwinkle
                - isActivitySender:
                    user: aahill
                - isActivitySender:
                    user: laujan
                - isActivitySender:
                    user: patrickfarley
                - isActivitySender:
                    user: jboback
                - isActivitySender:
                    user: heidisteen
                - isActivitySender:
                    user: haileytap
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - Please don't sign off on this PR. The area owners will sign off once they've reviewed your contribution.
          - mentionUsers:
              mentionees:
                - eric-urban
                - nitinme
                - mrbullwinkle
                - aahill
                - laujan
                - patrickfarley
                - jboback
                - heidisteen
                - haileytap
              replyTemplate: ${mentionees} - Please review this PR and sign off when you're ready to merge it.
              assignMentionees: True # This part probably won't work since the bot doesn't have write perms.
          - addLabel:
              label: needs-human-review
